### ISSUE TITLE
Add Turin, Italy

### ISSUE THREAD

**Issue by garro95** [graphhopper/open-traffic-collection#13]
5t provides opendata for the traffic in the city of Turin, Italy and some nearby area in the form of a CSV with a granularity of 5 minutes.
Informations about the dataset are in this pdf http://www.5t.torino.it/wp-content/uploads/2016/04/flussi_traffico_rt.pdf (ITA)
The dataset is available here: http://opendata.5t.torino.it/get_fdt

**Comment by karussell** [comment]
Thanks a lot, added!

**Comment by garro95** [comment]
I'd like to signal also that the same agency provides info about some parking areas and controlled traffic zones.
