### ISSUE TITLE
The Netherlands

### ISSUE THREAD

**Issue by skinkie** [graphhopper/open-traffic-collection#2]
NDW (Dutch governmental organisation) publishes an open data service.

Data and measurements:
ftp://83.247.110.3/

About and some documentation:
http://83.247.110.3/ndwOpenAVG/Default.aspx

**Comment by karussell** [comment]
Thanks! What is the coverage, whole Netherlands or certain cities?

**Comment by karussell** [comment]
I've added it.

**Comment by skinkie** [comment]
Basically the highways, and everything else that has sensors ;)

**Comment by karussell** [comment]
Okay, thanks!

**Comment by karussell** [comment]
I've got some official response with some more infos about this service

> It is correct that we publish traffic data as open data. Information about our open data can be found on www.ndw.nu/pagina/nl/103/datalevering/120/open_data/ but this information is in Dutch.
> For the historic data there are two options: 
> * the basic module (basismodule). With this module you can easily obtain data from a maximum of 10 locations. The link to this module is: http://ndwopendata.kxa.nl/. There is a maximum of 5 request per day.
> * With the export module you can obtain historic data in xml format for all locations. The maximum size of the request is 12500 MB which amounts to at least 7 days of data. Per IP address, a maximum of 3 simultaneous requests are possible. You can find this module here: http://83.247.110.3/OpenDataHistorie
