### ISSUE TITLE
new 40 city mega-dataset

### ISSUE THREAD

**Issue by philshem** [graphhopper/open-traffic-collection#22]
https://utd19.ethz.ch/

> UTD19 is a large-scale traffic dataset from over 23541 stationary detectors on urban roads in 40 cities worldwide making it the largest multi-city traffic dataset publically available. 

and discussion on HN: https://news.ycombinator.com/item?id=24405632

**Comment by ambuehll** [comment]
Hi there,
creator of UTD19 here. 

Happy to cross-reference the data sets in a way, if you want. 

see also: https://github.com/ambuehll/UTD19/
Cheers,
Lukas

**Comment by ambuehll** [comment]
It's under CC BY-NC-SA 4.0 by request of the published cities. Whatever is easiest for you :) I won't be uploading the data to github directly, as we'll want to channel everything through **https://utd19.ethz.ch/**.

**Comment by karussell** [comment]
> It's under CC BY-NC-SA 4.0

Ah, perfect. We should include this the license for the other data sets too.

Have added it here: https://github.com/graphhopper/open-traffic-collection/blob/master/README.md#europe-misc

Please simply submit a PR if you would like to have a change :)
