### ISSUE TITLE
Broken link for Switzerland

### ISSUE THREAD

**Issue by robinwyss** [graphhopper/open-traffic-collection#3]
The link for the traffic data from Switzerland is broken, it points to https://www.astra.admin.ch/verkehrsdaten/ which doesn't exist, I believe the correct link should be: 
https://www.astra.admin.ch/astra/en/home/dokumentation/verkehrsdaten.html

**Comment by karussell** [comment]
Thanks!

**Comment by Buildstarted** [comment]
Looks like this needs to be updated again: https://www.astra.admin.ch/astra/de/home/dokumentation/daten-informationsprodukte/verkehrsdaten.html
