### ISSUE TITLE
France DATEX-II data URL has changed

### ISSUE THREAD

**Issue by soria-aurelien** [graphhopper/open-traffic-collection#35]
Hello, 
The link provided in your repository for France DATEX-II API seems outdated.
The new link governmental links are :
https://transport.data.gouv.fr/datasets/etat-de-circulation-en-temps-reel-sur-le-reseau-national-routier-non-concede for real time traffic
https://transport.data.gouv.fr/datasets/evenements-routiers-sur-le-reseau-routier-national-non-concede for traffic events

**Comment by karussell** [comment]
Can you provide a pull request?

**Comment by soria-aurelien** [comment]
Here is the requested pull request :
https://github.com/graphhopper/open-traffic-collection/pull/36

**Comment by karussell** [comment]
Thanks!
