### ISSUE TITLE
Open Traffic Data project 

### ISSUE THREAD

**Issue by scubachristophe** [graphhopper/open-traffic-collection#8]
Open Traffic Data project now directs to http://www.military-technologies.net/

**Comment by karussell** [comment]
It was before too, but it looks like the blog post is gone :/ 

http://military-technologies.net/2017/01/08/open-traffic-data-to-revolutionize-transport/

**Comment by karussell** [comment]
Probably we should use this here instead?
http://www.worldbank.org/en/news/feature/2016/12/19/open-traffic-data-to-revolutionize-transport

**Comment by karussell** [comment]
Yes, it looks like it is the same https://web.archive.org/web/20170310121258/http://military-technologies.net/2017/01/08/open-traffic-data-to-revolutionize-transport/

**Comment by karussell** [comment]
Thanks for reporting!
